twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        timezone: America/Vancouver
        format: Y-m-d g:i:s A
        interval_format: '%%d days'
    form_themes:
        - '@NinesUtil/form/bootstrap_5_horizontal_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - 'jquery.collection.html.twig'
    globals:
        asset_prefix: '%env(default::string:ROUTE_BASE)%'
        matomo_enabled: '%dhil.matomo_enabled%'
        matomo_url: '%dhil.matomo_url%'
        matomo_siteid: '%dhil.matomo_siteid%'
        matomo_domain: '%dhil.matomo_domain%'
        comment_service: '@Nines\FeedbackBundle\Services\CommentService'
        nines_editor_config: js/editor-config.js
        linker: '@Nines\UtilBundle\Services\EntityLinker'
        git_repo: '%env(default::string:GIT_REPO)%'
        git_commit: '%env(default::string:GIT_COMMIT)%'
        git_commit_short: '%env(default::string:GIT_COMMIT_SHORT)%'
        git_branch: '%env(default::string:GIT_BRANCH)%'
        git_tag: '%env(default::string:GIT_TAG)%'

when@test:
    twig:
        strict_variables: true