sudo: false

language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    
cache: apt

env:
    global:
        - SYMFONY_ENV=test

before_script:
  - composer install -n -o
  - echo 'date.timezone = America/Vancouver' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./bin/phpunit
        