version: '3.8'
services:
  db:
    container_name: doceww_db
    image: mariadb:10.11
    ports:
      - "13306:3306"
    volumes:
      - .data/mariadb:/var/lib/mysql
      - ./docker/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d
      # # HACK: easy sql script running for setting up db
      # - ./doceww.sql:/doceww.sql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: doceww
      MARIADB_USER: doceww
      MARIADB_PASSWORD: password
    healthcheck:
      test: mysql doceww -u doceww -ppassword -e 'SELECT 1;' || exit 1
      interval: 2s
      retries: 120

  elasticsearch:
    container_name: doceww_elasticsearch
    image: elasticsearch:8.9.2
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
      - .data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: true
      ELASTIC_PASSWORD: password

  app:
    container_name: doceww_app
    # image: dhil/doceww
    build:
      context: .
      target: doceww
    ports:
      - "8080:80"
    volumes:
      # code for development
      - .:/var/www/html

      # use the container's var (for cache, etc)
      - /var/www/html/var
      # persist file uploads in .data
      - .data/app/data:/var/www/html/data
      # persist logs
      - .data/app/log:/var/www/html/var/log

      # use the container's node_modules & vendor folders (don't override)
      - /var/www/html/public/node_modules
      - /var/www/html/public/bundles
      - /var/www/html/vendor
    healthcheck:
      test: curl --fail http://localhost/health.php || exit 1
      interval: 2s
      retries: 120
    depends_on:
      db:
        condition: service_healthy

  docs:
    container_name: doceww_docs_watcher
    build:
      context: .
      target: doceww-docs
    command: sphinx-autobuild source _site/
    volumes:
      - ./docs:/app
      - ./public/docs/sphinx:/app/_site

  mail:
    container_name: doceww_mail
    image: jcalonso/mailhog:v1.0.1
    ports:
      - "8025:8025"