<?php

namespace Nines\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Nines\BlogBundle\Entity\PostStatus;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function listQuery($private = false) {
        $qb = $this->createQueryBuilder('e');
        if( ! $private ) {
            $qb->andWhere('e.public = true');
        }
        $qb->orderBy('e.weight', 'asc');
        return $qb->getQuery();
    }
    
    public function fulltextQuery($q, $private = false) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect("MATCH_AGAINST (e.title, e.searchable, :q 'IN BOOLEAN MODE') as HIDDEN score");
        $qb->andWhere("MATCH_AGAINST (e.title, e.searchable, :q 'IN BOOLEAN MODE') > 0");
        if( ! $private) {
            $qb->andWhere('e.public = true');
        }
        $qb->orderBy('score', 'desc');
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }
    
}
