<?php

namespace Nines\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Nines\BlogBundle\Entity\PostStatus;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {

    public function fulltextQuery($q) {
        $qb = $this->createQueryBuilder('e');
        $qb->addSelect("MATCH_AGAINST (e.title, e.searchable, :q 'IN BOOLEAN MODE') as HIDDEN score");
        $qb->add('where', "MATCH_AGAINST (e.title, e.searchable, :q 'IN BOOLEAN MODE') > 0");
        $qb->orderBy('score', 'desc');
        $qb->setParameter('q', $q);
        return $qb->getQuery();
    }
    
    public function recentQuery($private = false) {
        $em = $this->getEntityManager();
        $qb = $this->createQueryBuilder('e');
        if( ! $private) {
            $statuses = $em->getRepository(PostStatus::class)->findBy(array(
                'public' => true,
            ));
            $qb->andWhere('e.status = :status');
            $qb->setParameter('status', $statuses);
        }
        $qb->orderBy('e.id', 'DESC');
        return $qb->getQuery();
    }
}
