<?php

namespace AppBundle\Repository;

use AppBundle\Entity\DateYear;
use AppBundle\Entity\Person;
use AppBundle\Entity\Publication;
use Doctrine\ORM\EntityRepository;

/**
 * DateYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateYearRepository extends EntityRepository
{
    public function getEntity(DateYear $dateYear) {
        $personRepo = $this->_em->getRepository(Person::class);
        if(($entity = $personRepo->findOneBy(array('birthDate' => $dateYear)))) {
            return $entity;
        }
        if(($entity = $personRepo->findOneBy(array('deathDate' => $dateYear)))) {
            return $entity;
        }
        $publicationRepository = $this->_em->getRepository(Publication::class);
        return $publicationRepository->findOneBy(array('dateYear' => $dateYear));
    }
}
