<?php

namespace AppBundle\Repository;

/**
 * DateYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateYearRepository extends \Doctrine\ORM\EntityRepository
{
}
