<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Exception;

/**
 * PeriodicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodicalRepository extends PublicationRepository
{
    public function findPeriodical($title, $placeName = null) {
        $qb = $this->createQueryBuilder('p');
        $qb->andWhere('p.title = :title');
        $qb->setParameter('title', $title);
        
        try {
            return $qb->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
            throw new Exception("Duplicate publication detected:{$e->getMessage()} - " . implode(':', ['periodical', $title, $placeName]));
        }
    }
}
