<?php

namespace AppBundle\Repository;

/**
 * PeriodicalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodicalRepository extends \Doctrine\ORM\EntityRepository
{
}
