imports:
    - { resource: config_dev.yml }
    - { resource: parameters.yml }

liip_functional_test:
    cache_sqlite_db: true
    command_verbosity: debug
    command_decoration: false
        
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     "%kernel.cache_dir%/test.sqlite"
                charset:  UTF8
                logging: false
                profiling: false
                
security:
    firewalls:
        main:
            pattern: ^/
            http_basic: ~
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
