<?php

namespace App\Repository;

use App\Entity\DateYear;
use App\Entity\Person;
use App\Entity\Place;
use App\Entity\Publication;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DateYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateYearRepository extends ServiceEntityRepository {

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, DateYear::class);
    }

    public function getEntity(DateYear $dateYear) {
        $personRepo = $this->_em->getRepository(Person::class);
        if(($entity = $personRepo->findOneBy(array('birthDate' => $dateYear)))) {
            return $entity;
        }
        if(($entity = $personRepo->findOneBy(array('deathDate' => $dateYear)))) {
            return $entity;
        }
        $publicationRepository = $this->_em->getRepository(Publication::class);
        return $publicationRepository->findOneBy(array('dateYear' => $dateYear));
    }
}
