services:
    ceww.importer.author:
        class: AppBundle\Services\AuthorImporter
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setTitleCaser, ["@nines.util.title_caser"]]
            - [ setLogger, ["@monolog.logger"]]
            
    ceww.importer.periodical:
        class: AppBundle\Services\PeriodicalImporter
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setTitleCaser, ["@nines.util.title_caser"]]
            - [ setLogger, ["@monolog.logger"]]
            
    ceww.merger:
        class: AppBundle\Services\Merger
        calls:
            - [ setDoctrine, ["@doctrine"]]
            - [ setLogger, ["@monolog.logger"]]
